import NavBar from "./component/NavBar";
import "./globals.css";

export const metadata = {
  title: "Hyang",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className="background">
      <body className="flex flex-col h-screen overflow-hidden">
        <NavBar />
        {/* 배경 박스 */}
        <div className="bg-[#e6dfc7] mx-5 mb-5 rounded-lg flex-1 overflow-y-auto custom-scrollbar">
          <div className="p-3">{children}</div>
        </div>
      </body>
    </html>
  );
}
