import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Hyang",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className="background flex flex-col py-5 gap-2">

        <nav className="flex justify-between bg-[#1c1c2b] rounded-lg mx-5 h-[3rem] w-auto items-center p-3 text-white text-[0.9rem]">
          <div className="flex gap-5 items-center">
            <Link href="/" className="text-[1.2rem]">한지공방 한지향</Link>
            <Link href="/about">공방소개</Link>
            <Link href="/lamp">한지조명</Link>
            <Link href="/student">수강생모집</Link>
            <Link href="/gallery">갤러리</Link>
          </div>
          <div className="flex gap-5 items-center"> 
            <Link href="/signin">로그인</Link>
            <Link href="/signup">회원가입</Link>
          </div>
        </nav>

        <div className="bg-[#000] mx-5 p-3 rounded-lg">
          {children}
        </div>

      </body>
    </html>
  );
}
